version: 1.0.1.{build}-beta
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    powershell .\install-android-sdk.ps1

artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
- path: ./component/*.xam
  name: Component
